### PR TITLE
Publish vscode extension using github action

### LINKED ISSUE #4: publish vscode ext to vscode registry

### PR DESCRIPTION
**Pull request by sweetim**
fixed #4 

using this github action
- https://github.com/marketplace/actions/publish-vs-code-extension

vscode ext publish reference
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension

### CODE REVIEW

**Comment by sweetim** [comment]
need to configure the token by the repo owner

- [ ]  OPEN_VSX_TOKEN 
- [ ] VS_MARKETPLACE_TOKEN

**Comment by msakuta** [comment]
Nice! Actualy I was postponing publishing the extension to the marketplace before completing one task.
Currently we use .txt extension for the behavior tree config, but it's too generic and intrusive to most of the users. I want to decide a specific extension to avoid collsion with normal text files.

So we come to the most difficult part - deciding the name!
Naive name would be .btl from behavior-tree-lite. Does that sound good?
Or should we include "Rust" part and use .rbtl?

**Comment by sweetim** [comment]
how about `.btc` - behavior tree config file
a generic name then this could be the de facto standard for other implementation of behavior tree in the future?

and also we need to create an icon for the extension?

- [ ] create extension icon

**Comment by msakuta** [comment]
btc sounds like a new cryptocurrency! I like it.

I tried to make a file icon in [this branch](https://github.com/msakuta/rusty-behavior-tree-lite/tree/code-icon):

bt-logo-blu

But it's too small on VSCode file browser to read what's written. Designing an icon is harder than I thought.

image

**Comment by msakuta** [comment]
How about this design? It implies the gear of Rust logo and more visible on VSCode.

bt-logo-blu

image

**Comment by sweetim** [comment]
yeah the new design looks good!
have a wild idea for the logo

how about put the gear at the bottom to signify it as a root of a tree
and at the top of the gear is letter T

**Comment by msakuta** [comment]
Like this?

bt-logo-blu

It looks too small in VSCode, it looks like just a ring.

image

**Comment by msakuta** [comment]
Or omit B and just like this?

bt-logo-blu

It looks more like a gear. It may be better fit to other icon styles in VSCode.

image

**Comment by sweetim** [comment]
use half gear? then it looks like tree 

image

**Comment by sweetim** [comment]
or something like this lol?

image

**Comment by msakuta** [comment]
> use half gear? then it looks like tree
> 
> image

I like this one. It's large enough to show gear cogs.

With transparency and svg:

bt-logo-blu


image

**Comment by msakuta** [comment]
I got yet another idea. A [faucet handle](https://www.google.com/search?q=faucet+handle&sxsrf=AJOqlzXMjKU54NzHR4OYYzbHYfDGxYFVbw:1677410399646&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjWlo3YiLP9AhUZtlYBHcJ2B8gQ_AUoAXoECAEQAw&biw=1920&bih=969&dpr=1) attached to "B", which implies adjusting the behavior.

It doesn't represent the "tree" part, but I guess the icon is too small to express it. Also it's kind of too small to show recognizable gear cogs.

bt-logo-blu


image

**Comment by sweetim** [comment]
the faucet icon is very nice too! i like it!

so, you are the owner you have to decide! :)

**Comment by msakuta** [comment]
Yeah I will go with faucet design for now, we can revisit any time if someone comes up with a better idea

**Comment by msakuta** [comment]
Unfortunately `HaaLeo/publish-vscode-extension@v1` doesn't seem to work with a project in a subdirectory of a repository. I tried to set `packagePath` but it fails to publish with an error that it can't find the icon. But I could publish the extension manually, so I guess I have to make a plain command line action to publish, or isolate the VSCode extension to a separate repository.

**Pull request merged**
